name: autorun
on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 * * * *'
jobs:
    build:
        name: build and run
        runs-on: ubuntu-16.04
        steps:
            - name: Set up Go 1.16
              uses: actions/setup-go@v1
              with:
                  go-version: 1.16
              id: go

            - name: Check out source code
              uses: actions/checkout@v1

            - name: build
              run: |
                  go build -o Spider *.go

            - name: run
              run: |
                  ./Spider
              env:
                  MONGODB_URI: ${{ secrets.MONGODB_URI  }}
